<html>
    <head>
        <link rel="icon" href="general/images/RESO_icon_RGB.png" sizes="16x16" type="image/png">
        <title>RESO-Compliance Tool</title>
        
        <!-- Java scripts -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <script src="general/js/jquery-1.5.2.min.js" type="text/javascript"></script>
        
        <script src="general/js/hideshow.js" type="text/javascript"></script>
        <script src="general/js/jquery.tablesorter.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="general/js/jquery.equalHeight.js"></script>
        
        <!-- Style sheets -->
        <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/sandstone/bootstrap.min.css'>
        <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="general/css/layout.css" type="text/css" media="screen" />
        
        <!-- Angular -->
        <script src= "https://code.angularjs.org/1.4.2/angular.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.js"></script>
        <script src="https://code.angularjs.org/1.4.2/angular-cookies.js"></script>  
        
        <script src="app/app.js" type="text/javascript"></script>
        <script src="app/app.module.js" type="text/javascript"></script>
        <script src="general/js/angular-datepicker.js" type="text/javascript"></script>
        <link href="general/css/angular-datepicker.css" rel="stylesheet" type="text/css"/>
        <!-- Controllers -->
        <script src="app/components/login/loginController.js" type="text/javascript"></script>
        <script src="app/components/login/loginService.js" type="text/javascript"></script>
        <script src="app/common/sidebar/sidebarDirective.js" type="text/javascript"></script>
        <script src="app/components/dashboard/dashboardController.js" type="text/javascript"></script>
        <script src="app/components/dashboard/dashboardService.js" type="text/javascript"></script>
        <script src="app/components/metadata/metadataController.js" type="text/javascript"></script>
        <script src="app/components/mls/mlsController.js" type="text/javascript"></script>
        <script src="app/components/mls/mlsService.js" type="text/javascript"></script>
        <script src="app/components/mlsList/mlsListController.js" type="text/javascript"></script>
        <script src="app/components/mlsList/mlsListService.js" type="text/javascript"></script>
    </head>
    <body ng-app="myApp">
        <header id="header">
            <hgroup>
                <div class="header_logo"><img src="general/images/RESO_logo_RGB.jpg" width="120"></div>
            </hgroup>
	</header> <!-- end of header bar -->
        <div ui-view="sideView"></div>
        <!-- end of left side bar -->
        <div ui-view="mainView"></div>
        <!-- end of right side main content -->
    </body>
    <footer>
        &copy; softincubator.com. All rights reserved.     
    </footer>
</html>